version: "3.8"
services:
  splunk:
    image: "splunk/splunk:latest"
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: Admin11!
      SPLUNK_HEC_TOKEN: admin11

  consul:
    image: consul
    ports:
      - "8500:8500"
    environment:
      CONSUL_BIND_INTERFACE: eth0
